'use strict';
const STORAGE_KEY='luis-transformation-v1';
const DEFAULT_FOODS=[
{id:'chicken',name:'Blanc de poulet',kcal:165,protein:31,carbs:0,fat:3.6},{id:'skyr',name:'Skyr nature',kcal:63,protein:11,carbs:4,fat:.2},{id:'rice',name:'Riz basmati cuit',kcal:130,protein:2.7,carbs:28,fat:.3},{id:'oats',name:'Flocons d’avoine',kcal:372,protein:13.5,carbs:58.7,fat:7},{id:'banana',name:'Banane',kcal:89,protein:1.1,carbs:22.8,fat:.3},{id:'egg',name:'Œuf entier',kcal:143,protein:12.6,carbs:.7,fat:9.5},{id:'salmon',name:'Saumon',kcal:208,protein:20,carbs:0,fat:13},{id:'whey',name:'Whey isolate',kcal:370,protein:84,carbs:3,fat:1.5},{id:'greek',name:'Yaourt grec 0%',kcal:59,protein:10.3,carbs:3.6,fat:.4},{id:'pasta',name:'Pâtes cuites',kcal:157,protein:5.8,carbs:30.9,fat:.9},{id:'oliveoil',name:'Huile d’olive',kcal:884,protein:0,carbs:0,fat:100},{id:'avocado',name:'Avocat',kcal:160,protein:2,carbs:8.5,fat:14.7},{id:'bread',name:'Pain complet',kcal:247,protein:13,carbs:41,fat:4.2},{id:'beef',name:'Bœuf maigre',kcal:180,protein:27,carbs:0,fat:8},{id:'potato',name:'Pomme de terre cuite',kcal:87,protein:1.9,carbs:20,fat:.1}
];
const MEALS={breakfast:'Petit-déjeuner',lunch:'Déjeuner',snack:'Collation',dinner:'Dîner'};
const WORKOUT_PRESETS={
Push:{target:'Pectoraux · épaules · triceps',exercises:[
{name:'Développé couché barre',sets:4,reps:'6–8',rest:'2 min'},
{name:'Développé incliné haltères',sets:3,reps:'8–10',rest:'90 s'},
{name:'Développé épaules haltères',sets:3,reps:'8–10',rest:'90 s'},
{name:'Élévations latérales',sets:3,reps:'12–15',rest:'60 s'},
{name:'Dips ou pompes',sets:3,reps:'8–12',rest:'90 s'},
{name:'Extension triceps poulie',sets:3,reps:'10–15',rest:'60 s'}]},
Pull:{target:'Dos · arrière d’épaules · biceps',exercises:[
{name:'Tractions assistées ou tirage vertical',sets:4,reps:'6–10',rest:'2 min'},
{name:'Rowing barre ou machine',sets:4,reps:'8–10',rest:'90 s'},
{name:'Tirage horizontal poulie',sets:3,reps:'10–12',rest:'90 s'},
{name:'Face pull',sets:3,reps:'12–15',rest:'60 s'},
{name:'Curl haltères',sets:3,reps:'8–12',rest:'60 s'},
{name:'Curl marteau',sets:2,reps:'10–12',rest:'60 s'}]},
Legs:{target:'Quadriceps · ischios · fessiers · mollets',exercises:[
{name:'Squat',sets:4,reps:'6–8',rest:'2 min'},
{name:'Presse à cuisses',sets:3,reps:'8–12',rest:'90 s'},
{name:'Soulevé de terre roumain',sets:3,reps:'8–10',rest:'90 s'},
{name:'Fentes marchées',sets:3,reps:'10 / jambe',rest:'75 s'},
{name:'Leg curl',sets:3,reps:'10–15',rest:'60 s'},
{name:'Mollets debout',sets:3,reps:'12–20',rest:'60 s'}]},
'Haut du corps':{target:'Pectoraux · dos · épaules · bras',exercises:[
{name:'Développé couché',sets:4,reps:'6–8',rest:'2 min'},
{name:'Tirage vertical',sets:4,reps:'8–10',rest:'90 s'},
{name:'Développé épaules',sets:3,reps:'8–10',rest:'90 s'},
{name:'Rowing assis',sets:3,reps:'8–12',rest:'90 s'},
{name:'Superset biceps / triceps',sets:3,reps:'10–12',rest:'60 s'}]},
'Bas du corps':{target:'Jambes · fessiers · gainage',exercises:[
{name:'Squat ou hack squat',sets:4,reps:'6–10',rest:'2 min'},
{name:'Soulevé de terre roumain',sets:3,reps:'8–10',rest:'90 s'},
{name:'Presse à cuisses',sets:3,reps:'10–12',rest:'90 s'},
{name:'Leg curl',sets:3,reps:'10–15',rest:'60 s'},
{name:'Gainage',sets:3,reps:'40–60 s',rest:'45 s'}]},
'Full body':{target:'Corps entier',exercises:[
{name:'Squat',sets:3,reps:'6–8',rest:'2 min'},
{name:'Développé couché',sets:3,reps:'6–8',rest:'2 min'},
{name:'Tirage vertical',sets:3,reps:'8–10',rest:'90 s'},
{name:'Soulevé de terre roumain',sets:3,reps:'8–10',rest:'90 s'},
{name:'Développé épaules',sets:2,reps:'8–12',rest:'75 s'}]}}
let activeWorkoutExercises=[];
function latestExerciseWeight(name){for(const w of [...data.strength].sort((a,b)=>b.date.localeCompare(a.date))){const ex=(w.workoutExercises||[]).find(x=>x.name===name&&num(x.weight)>0);if(ex)return num(ex.weight)}return ''}
function renderWorkoutPreset(){const type=$('strengthType').value,preset=WORKOUT_PRESETS[type]||WORKOUT_PRESETS.Push;$('workoutTitle').textContent=`Séance ${type}`;$('workoutTarget').textContent=preset.target;activeWorkoutExercises=preset.exercises.map((e,i)=>({...e,weight:latestExerciseWeight(e.name),done:false,index:i}));$('exerciseRows').innerHTML=activeWorkoutExercises.map((e,i)=>`<article class="exercise-row"><div class="exercise-main"><strong>${escapeHtml(e.name)}</strong><small>${e.sets} séries × ${e.reps} reps · repos ${e.rest}</small></div><label class="weight-field"><span>Poids</span><div><input type="number" step="0.5" min="0" inputmode="decimal" data-exercise-weight="${i}" value="${e.weight}" placeholder="kg"><b>kg</b></div></label></article>`).join('')}
function collectWorkoutExercises(){return activeWorkoutExercises.map((e,i)=>({...e,weight:num(document.querySelector(`[data-exercise-weight="${i}"]`)?.value)}))}

const initialData={daily:{},supplements:{},nutrition:{},strength:[],running:[],customFoods:[],profile:{initialWeight:81.5,initialWaist:92,proteinGoal:170,calorieGoal:2400,creatineGoal:5}};
let data=loadData(),selectedFood=null,deferredPrompt=null;
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),num=(v,fb=0)=>Number.isFinite(Number(v))?Number(v):fb,fmt=n=>Math.round(n*10)/10;
function clone(v){return JSON.parse(JSON.stringify(v))}function loadData(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');return {...clone(initialData),...p,profile:{...initialData.profile,...(p.profile||{})},customFoods:p.customFoods||[]}}catch{return clone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll()}function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2000)}
function fmtDate(d){return new Intl.DateTimeFormat('fr-CH',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function setDefaults(){['dailyDate','supplementDate','nutritionDate','strengthDate','runDate'].forEach(id=>$(id).value=today())}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.target===name));$('pageTitle').textContent={dashboard:'Tableau de bord',daily:'Saisie quotidienne',nutrition:'Nutrition',supplements:'Compléments',strength:'Musculation',running:'Course',history:'Historique',settings:'Plus'}[name]||'Luis Transformation';$('moreSheet').classList.add('hidden');if(name==='nutrition')renderNutrition();if(name==='history')drawChart();scrollTo(0,0)}
function nutritionDay(date=today()){const n=data.nutrition[date];if(!n)return {entries:[]};if(Array.isArray(n.entries))return n;const legacyProtein=num(n.protein);return legacyProtein?{...n,entries:[],legacyProtein}:{...n,entries:[]}}
function totals(date=today(),meal=null){const n=nutritionDay(date);const list=meal?n.entries.filter(e=>e.meal===meal):n.entries;const t=list.reduce((a,e)=>({kcal:a.kcal+num(e.kcal),protein:a.protein+num(e.protein),carbs:a.carbs+num(e.carbs),fat:a.fat+num(e.fat)}),{kcal:0,protein:0,carbs:0,fat:0});if(!meal&&n.legacyProtein&&!t.protein)t.protein=n.legacyProtein;return t}
function renderNutrition(){const date=$('nutritionDate').value||today(),t=totals(date);$('nutKcal').textContent=Math.round(t.kcal);$('nutProtein').textContent=fmt(t.protein);$('nutCarbs').textContent=fmt(t.carbs);$('nutFat').textContent=fmt(t.fat);$('kcalBar').style.width=`${Math.min(100,t.kcal/data.profile.calorieGoal*100)}%`;$('proteinHint').textContent=t.protein>=data.profile.proteinGoal?'Objectif protéines atteint ✅':`Il te manque ${Math.ceil(data.profile.proteinGoal-t.protein)} g de protéines.`;const host=$('mealSections');host.innerHTML='';Object.entries(MEALS).forEach(([key,label])=>{const n=nutritionDay(date),list=n.entries.filter(e=>e.meal===key),mt=totals(date,key),sec=document.createElement('section');sec.className='card section-card';sec.innerHTML=`<div class="meal-head"><h2 class="meal-title">${label}</h2><span class="meal-total">${Math.round(mt.kcal)} kcal · ${fmt(mt.protein)} g prot.</span></div>${list.length?list.map(e=>`<div class="food-row"><div><strong>${escapeHtml(e.name)}</strong><small>${e.grams} g · ${Math.round(e.kcal)} kcal · ${fmt(e.protein)} g prot.</small></div><button class="delete" data-food-delete="${e.id}">×</button></div>`).join(''):'<div class="empty">Aucun aliment</div>'}`;host.appendChild(sec)});renderFoodSearch($('foodSearch').value)}
function foods(){return [...data.customFoods,...DEFAULT_FOODS]}function renderFoodSearch(q=''){const s=q.trim().toLowerCase(),list=(s?foods().filter(f=>f.name.toLowerCase().includes(s)):foods().slice(0,7)).slice(0,12);$('foodResults').innerHTML=list.map(f=>`<div class="food-result" data-food="${f.id}"><div><strong>${escapeHtml(f.name)}</strong><small>pour 100 g</small></div><small>${f.kcal} kcal · ${f.protein} g prot.</small></div>`).join('')}
function openFood(f){selectedFood=f;$('dialogFoodName').textContent=f.name;$('dialogFoodMacros').textContent=`Pour 100 g : ${f.kcal} kcal · ${f.protein} g protéines · ${f.carbs} g glucides · ${f.fat} g lipides`;$('gramsInput').value=100;$('foodDialog').showModal()}
function latestDaily(field,fallback){const r=Object.entries(data.daily).filter(([,v])=>v[field]!==''&&v[field]!=null).sort(([a],[b])=>b.localeCompare(a));return r.length?num(r[0][1][field],fallback):fallback}
function getWeekBounds(){const d=new Date(),day=(d.getDay()+6)%7,start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);return{start,end}}function inCurrentWeek(ds){const d=new Date(ds+'T12:00:00'),{start,end}=getWeekBounds();return d>=start&&d<=end}
function renderDashboard(){const date=today(),daily=data.daily[date]||{},sup=data.supplements[date]||{},t=totals(date),weight=latestDaily('weight',data.profile.initialWeight),waist=latestDaily('waist',data.profile.initialWaist);$('todayLabel').textContent=new Intl.DateTimeFormat('fr-CH',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('currentWeight').textContent=`${weight.toFixed(1).replace('.',',')} kg`;$('currentWaist').textContent=`${waist.toFixed(1).replace('.',',')} cm`;$('weightDelta').textContent=`${(weight-data.profile.initialWeight).toFixed(1)} kg`;$('waistDelta').textContent=`${(waist-data.profile.initialWaist).toFixed(1)} cm`;$('caloriesToday').textContent=`${Math.round(t.kcal)} / ${data.profile.calorieGoal}`;$('calorieStatus').textContent=t.kcal>=data.profile.calorieGoal*.9?'Bien avancé':'À compléter';$('proteinToday').textContent=`${fmt(t.protein)} / ${data.profile.proteinGoal} g`;$('proteinStatus').textContent=t.protein>=data.profile.proteinGoal?'Objectif atteint':'À compléter';const creatine=sup.creatineTaken?num(sup.creatineAmount,5):0;let checks=0;if(daily.weight)checks++;if(daily.waist)checks++;if(daily.sleep)checks++;if(daily.water)checks++;if(t.protein>=data.profile.proteinGoal)checks++;if(creatine>=5)checks++;if(data.strength.some(x=>x.date===date)||data.running.some(x=>x.date===date))checks++;$('dayScore').textContent=Math.round(checks/7*100);const strength=data.strength.filter(x=>inCurrentWeek(x.date)).length,runs=data.running.filter(x=>inCurrentWeek(x.date)).length,creatineDays=Object.entries(data.supplements).filter(([d,v])=>inCurrentWeek(d)&&v.creatineTaken&&num(v.creatineAmount)>=5).length;$('strengthProgress').value=Math.min(strength,4);$('runProgress').value=Math.min(runs,3);$('creatineProgress').value=Math.min(creatineDays,7);$('strengthCount').textContent=`${strength}/4`;$('runCount').textContent=`${runs}/3`;$('creatineCount').textContent=`${creatineDays}/7`;const {start,end}=getWeekBounds();$('weekRange').textContent=`${start.getDate()}–${end.getDate()}`}
function fillDaily(d){const v=data.daily[d]||{};['weight','waist','sleep','water'].forEach(k=>$(k).value=v[k]??'');$('stress').value=v.stress??3;$('energy').value=v.energy??3;$('hunger').value=v.hunger??3;$('dailyNote').value=v.note??'';updateRanges()}function fillSupp(d){const v=data.supplements[d]||{};$('creatineTaken').checked=!!v.creatineTaken;$('creatineAmount').value=v.creatineAmount??5;$('proteinPowderTaken').checked=!!v.proteinPowderTaken;$('proteinPowderAmount').value=v.proteinPowderAmount??30;$('otherSupplements').value=v.other??''}
function updateRanges(){['stress','energy','hunger','strengthRpe','runRpe'].forEach(id=>{const o=$(id+'Out');if(o)o.textContent=`${$(id).value}/${$(id).max}`})}function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderLists(){const mk=(x,type)=>{const detail=type==='strength'&&x.workoutExercises?.length?x.workoutExercises.map(e=>`${e.name} · ${e.sets}×${e.reps} · ${e.weight||0} kg`).join('\n'):escapeHtml(x.exercises||x.note||'');return `<article class="entry"><div class="entry-head"><div><h4>${type==='strength'?escapeHtml(x.type):`${escapeHtml(x.type)} — ${x.distance} km`}</h4><span class="muted">${fmtDate(x.date)}</span></div><button class="delete-entry" data-delete="${type}" data-id="${x.id}">×</button></div><p>${type==='strength'&&x.workoutExercises?.length?escapeHtml(detail):detail}</p></article>`};$('strengthList').innerHTML=[...data.strength].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=>mk(x,'strength')).join('');$('runList').innerHTML=[...data.running].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=>mk(x,'running')).join('');$('historyList').innerHTML=Object.entries(data.daily).sort(([a],[b])=>b.localeCompare(a)).slice(0,12).map(([d,v])=>`<article class="entry"><h4>${fmtDate(d)}</h4><div class="entry-meta">${v.weight?`<span class="chip">${v.weight} kg</span>`:''}${v.waist?`<span class="chip">${v.waist} cm</span>`:''}</div></article>`).join('')}
function drawChart(){const metric=$('chartMetric').value;let rows;if(['protein','calories'].includes(metric))rows=Object.keys(data.nutrition).map(date=>({date,value:metric==='protein'?totals(date).protein:totals(date).kcal}));else rows=Object.entries(data.daily).map(([date,v])=>({date,value:num(v[metric],NaN)}));rows=rows.filter(x=>Number.isFinite(x.value)).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);const c=$('progressChart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);$('chartEmpty').classList.toggle('hidden',rows.length>=2);if(rows.length<2)return;const vals=rows.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,p={l:55,r:20,t:25,b:35};ctx.strokeStyle='#79e6a3';ctx.lineWidth=5;ctx.beginPath();rows.forEach((r,i)=>{const x=p.l+(w-p.l-p.r)*i/(rows.length-1),y=p.t+(max-r.value)/range*(h-p.t-p.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function renderAll(){renderDashboard();renderLists();if(document.querySelector('[data-view="nutrition"]').classList.contains('active'))renderNutrition()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>b.classList.contains('more-button')?$('moreSheet').classList.remove('hidden'):showView(b.dataset.target)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));$('closeSheet').onclick=()=>$('moreSheet').classList.add('hidden');['stress','energy','hunger','strengthRpe','runRpe'].forEach(id=>$(id).oninput=updateRanges);$('strengthType').onchange=renderWorkoutPreset;
$('dailyDate').onchange=e=>fillDaily(e.target.value);$('supplementDate').onchange=e=>fillSupp(e.target.value);$('nutritionDate').onchange=renderNutrition;$('foodSearch').oninput=e=>renderFoodSearch(e.target.value);$('toggleCustomFood').onclick=()=>$('customFoodForm').classList.toggle('hidden');
$('dailyForm').onsubmit=e=>{e.preventDefault();const d=$('dailyDate').value;data.daily[d]={weight:$('weight').value,waist:$('waist').value,sleep:$('sleep').value,water:$('water').value,stress:num($('stress').value),energy:num($('energy').value),hunger:num($('hunger').value),note:$('dailyNote').value.trim()};save();toast('Journée enregistrée')};
$('supplementForm').onsubmit=e=>{e.preventDefault();const d=$('supplementDate').value;data.supplements[d]={creatineTaken:$('creatineTaken').checked,creatineAmount:num($('creatineAmount').value),proteinPowderTaken:$('proteinPowderTaken').checked,proteinPowderAmount:num($('proteinPowderAmount').value),other:$('otherSupplements').value.trim()};save();toast('Compléments enregistrés')};
$('strengthForm').onsubmit=e=>{e.preventDefault();const workoutExercises=collectWorkoutExercises();data.strength.push({id:crypto.randomUUID(),date:$('strengthDate').value,type:$('strengthType').value,duration:num($('strengthDuration').value),workoutExercises,exercises:workoutExercises.map(x=>`${x.name}: ${x.sets}×${x.reps} à ${x.weight||0} kg`).join('\n'),rpe:num($('strengthRpe').value),note:$('strengthNote').value.trim()});save();renderWorkoutPreset();toast('Séance enregistrée')};$('runForm').onsubmit=e=>{e.preventDefault();data.running.push({id:crypto.randomUUID(),date:$('runDate').value,type:$('runType').value,distance:num($('runDistance').value),duration:num($('runDuration').value),hr:num($('runHr').value),rpe:num($('runRpe').value),note:$('runNote').value.trim()});save();toast('Sortie ajoutée')};
$('foodResults').onclick=e=>{const el=e.target.closest('[data-food]');if(el)openFood(foods().find(f=>f.id===el.dataset.food))};$('confirmFood').onclick=e=>{e.preventDefault();const grams=num($('gramsInput').value);if(!selectedFood||grams<1)return;const d=$('nutritionDate').value,n=nutritionDay(d),r=grams/100;n.entries.push({id:crypto.randomUUID(),meal:$('mealSelect').value,name:selectedFood.name,grams,kcal:selectedFood.kcal*r,protein:selectedFood.protein*r,carbs:selectedFood.carbs*r,fat:selectedFood.fat*r});data.nutrition[d]=n;save();$('foodDialog').close();toast('Aliment ajouté')};
$('customFoodForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),food={id:`custom-${Date.now()}`,name:f.get('name'),kcal:num(f.get('kcal')),protein:num(f.get('protein')),carbs:num(f.get('carbs')),fat:num(f.get('fat'))};data.customFoods.unshift(food);save();e.target.reset();e.target.classList.add('hidden');toast('Aliment créé')};
$('mealSections').onclick=e=>{const b=e.target.closest('[data-food-delete]');if(!b)return;const d=$('nutritionDate').value,n=nutritionDay(d);n.entries=n.entries.filter(x=>x.id!==b.dataset.foodDelete);data.nutrition[d]=n;save()};$('copyYesterday').onclick=()=>{const d=new Date(($('nutritionDate').value||today())+'T12:00:00');d.setDate(d.getDate()-1);const prev=d.toISOString().slice(0,10),src=nutritionDay(prev);if(!src.entries.length)return toast('Aucun repas la veille');data.nutrition[$('nutritionDate').value]={entries:src.entries.map(x=>({...x,id:crypto.randomUUID()}))};save();toast('Journée copiée')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;data[b.dataset.delete]=data[b.dataset.delete].filter(x=>x.id!==b.dataset.id);save()});$('chartMetric').onchange=drawChart;$('exportBtn').onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`luis-transformation-${today()}.json`;a.click()};$('importInput').onchange=async e=>{try{data={...clone(initialData),...JSON.parse(await e.target.files[0].text())};save();toast('Données importées')}catch{alert('Fichier invalide')}};$('clearAllBtn').onclick=()=>{if(confirm('Effacer toutes les données ?')){data=clone(initialData);save()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
setDefaults();fillDaily(today());fillSupp(today());updateRanges();renderWorkoutPreset();renderAll();
