'use strict';
const STORAGE_KEY='luis-transformation-v1';
const initialData={daily:{},supplements:{},nutrition:{},strength:[],running:[],profile:{initialWeight:81.5,initialWaist:92,proteinGoal:170,creatineGoal:5}};
let data=loadData();
let deferredPrompt=null;
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const fmtDate=d=>new Intl.DateTimeFormat('fr-CH',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'));
const num=(v,fb=0)=>Number.isFinite(Number(v))?Number(v):fb;
function loadData(){try{return {...structuredClone(initialData),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(initialData)}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(data));renderAll()}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.remove('hidden');setTimeout(()=>el.classList.add('hidden'),2200)}
function setDefaults(){['dailyDate','supplementDate','nutritionDate','strengthDate','runDate'].forEach(id=>$(id).value=today())}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.target===name));const titles={dashboard:'Tableau de bord',daily:'Saisie quotidienne',supplements:'Compléments',nutrition:'Nutrition',strength:'Musculation',running:'Course',history:'Historique',settings:'Plus'};$('pageTitle').textContent=titles[name]||'Luis Transformation';$('moreSheet').classList.add('hidden');window.scrollTo({top:0,behavior:'smooth'});if(name==='history')drawChart();}
function getWeekBounds(){const d=new Date();const day=(d.getDay()+6)%7;const start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);return{start,end}}
function inCurrentWeek(dateStr){const d=new Date(dateStr+'T12:00:00');const {start,end}=getWeekBounds();return d>=start&&d<=end}
function latestDaily(field, fallback){const rows=Object.entries(data.daily).filter(([,v])=>v[field]!==''&&v[field]!=null).sort(([a],[b])=>b.localeCompare(a));return rows.length?num(rows[0][1][field],fallback):fallback}
function signDelta(current,initial,unit){const d=current-initial;if(Math.abs(d)<.05)return'Départ';return `${d>0?'+':''}${d.toFixed(1).replace('.',',')} ${unit}`}
function renderDashboard(){const date=today();const daily=data.daily[date]||{};const nut=data.nutrition[date]||{};const sup=data.supplements[date]||{};const weight=latestDaily('weight',data.profile.initialWeight);const waist=latestDaily('waist',data.profile.initialWaist);$('todayLabel').textContent=new Intl.DateTimeFormat('fr-CH',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('currentWeight').textContent=`${weight.toFixed(1).replace('.',',')} kg`;$('currentWaist').textContent=`${waist.toFixed(1).replace('.',',')} cm`;$('weightDelta').textContent=signDelta(weight,data.profile.initialWeight,'kg');$('waistDelta').textContent=signDelta(waist,data.profile.initialWaist,'cm');const protein=num(nut.protein);$('proteinToday').textContent=`${protein} / ${data.profile.proteinGoal} g`;$('proteinStatus').textContent=protein>=data.profile.proteinGoal?'Objectif atteint':'À compléter';const creatine=sup.creatineTaken?num(sup.creatineAmount,5):0;$('creatineToday').textContent=`${creatine} / ${data.profile.creatineGoal} g`;$('creatineStatus').textContent=creatine>=5?'Pris aujourd’hui':'À prendre';let checks=0,total=7;if(daily.weight)checks++;if(daily.waist)checks++;if(daily.sleep)checks++;if(daily.water)checks++;if(protein>=170)checks++;if(creatine>=5)checks++;if(data.strength.some(x=>x.date===date)||data.running.some(x=>x.date===date))checks++;$('dayScore').textContent=Math.round(checks/total*100);const strength=data.strength.filter(x=>inCurrentWeek(x.date)).length;const runs=data.running.filter(x=>inCurrentWeek(x.date)).length;const creatineDays=Object.entries(data.supplements).filter(([d,v])=>inCurrentWeek(d)&&v.creatineTaken&&num(v.creatineAmount)>=5).length;$('strengthProgress').value=Math.min(strength,4);$('runProgress').value=Math.min(runs,3);$('creatineProgress').value=Math.min(creatineDays,7);$('strengthCount').textContent=`${strength}/4`;$('runCount').textContent=`${runs}/3`;$('creatineCount').textContent=`${creatineDays}/7`;const {start,end}=getWeekBounds();$('weekRange').textContent=`${start.getDate()}–${end.getDate()} ${new Intl.DateTimeFormat('fr',{month:'short'}).format(end)}`;}
function fillDaily(date){const v=data.daily[date]||{};['weight','waist','sleep','water'].forEach(k=>$(k).value=v[k]??'');$('stress').value=v.stress??3;$('energy').value=v.energy??3;$('hunger').value=v.hunger??3;$('dailyNote').value=v.note??'';updateRanges()}
function fillSupp(date){const v=data.supplements[date]||{};$('creatineTaken').checked=!!v.creatineTaken;$('creatineAmount').value=v.creatineAmount??5;$('proteinPowderTaken').checked=!!v.proteinPowderTaken;$('proteinPowderAmount').value=v.proteinPowderAmount??30;$('otherSupplements').value=v.other??''}
function fillNutrition(date){const v=data.nutrition[date]||{};$('protein').value=v.protein??'';$('mealsQuality').value=v.mealsQuality??0;$('dietDeviation').value=v.dietDeviation??'none';$('nutritionNote').value=v.note??''}
function updateRanges(){['stress','energy','hunger','strengthRpe','runRpe'].forEach(id=>{const out=$(id+'Out');if(out)out.textContent=`${$(id).value}/${$(id).max}`})}
function renderLists(){const strength=[...data.strength].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);$('strengthList').innerHTML=strength.map(x=>entryHtml(x,'strength')).join('')||'<p class="muted center">Aucune séance enregistrée.</p>';const runs=[...data.running].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);$('runList').innerHTML=runs.map(x=>entryHtml(x,'running')).join('')||'<p class="muted center">Aucune sortie enregistrée.</p>';const daily=Object.entries(data.daily).sort(([a],[b])=>b.localeCompare(a)).slice(0,12);$('historyList').innerHTML=daily.map(([date,v])=>`<article class="entry"><div class="entry-head"><h4>${fmtDate(date)}</h4></div><div class="entry-meta">${v.weight?`<span class="chip">${v.weight} kg</span>`:''}${v.waist?`<span class="chip">${v.waist} cm</span>`:''}${v.sleep?`<span class="chip">${v.sleep} h sommeil</span>`:''}${v.water?`<span class="chip">${v.water} L eau</span>`:''}</div></article>`).join('')||'<p class="muted center">Aucune donnée quotidienne.</p>'}
function entryHtml(x,type){const title=type==='strength'?x.type:`${x.type} — ${x.distance} km`;const details=type==='strength'?`${x.duration} min · RPE ${x.rpe}/10`:`${x.duration} min · ${pace(x.distance,x.duration)} · RPE ${x.rpe}/10`;return `<article class="entry"><div class="entry-head"><div><h4>${title}</h4><span class="muted">${fmtDate(x.date)}</span></div><button class="delete-entry" data-delete="${type}" data-id="${x.id}" aria-label="Supprimer">×</button></div><div class="entry-meta"><span class="chip">${details}</span></div>${x.exercises?`<p>${escapeHtml(x.exercises)}</p>`:''}${x.note?`<p>${escapeHtml(x.note)}</p>`:''}</article>`}
function pace(distance,duration){if(!distance||!duration)return'—';const sec=Math.round(duration*60/distance);return `${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}/km`}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function drawChart(){const metric=$('chartMetric').value;const map={weight:['Poids','kg'],waist:['Tour de taille','cm'],protein:['Protéines','g'],sleep:['Sommeil','h']};let rows;if(metric==='protein')rows=Object.entries(data.nutrition).map(([date,v])=>({date,value:num(v.protein,NaN)}));else rows=Object.entries(data.daily).map(([date,v])=>({date,value:num(v[metric],NaN)}));rows=rows.filter(x=>Number.isFinite(x.value)).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);const canvas=$('progressChart'),ctx=canvas.getContext('2d'),w=canvas.width,h=canvas.height;ctx.clearRect(0,0,w,h);$('chartEmpty').classList.toggle('hidden',rows.length>=2);if(rows.length<2)return;const pad={l:58,r:22,t:25,b:45};const vals=rows.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;ctx.strokeStyle='#2b3241';ctx.fillStyle='#9aa3b2';ctx.lineWidth=1;ctx.font='22px -apple-system';for(let i=0;i<5;i++){const y=pad.t+(h-pad.t-pad.b)*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const val=max-range*i/4;ctx.fillText(val.toFixed(1),4,y+7)}ctx.strokeStyle='#79e6a3';ctx.lineWidth=5;ctx.lineJoin='round';ctx.beginPath();rows.forEach((r,i)=>{const x=pad.l+(w-pad.l-pad.r)*i/(rows.length-1);const y=pad.t+(max-r.value)/range*(h-pad.t-pad.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#79e6a3';rows.forEach((r,i)=>{const x=pad.l+(w-pad.l-pad.r)*i/(rows.length-1);const y=pad.t+(max-r.value)/range*(h-pad.t-pad.b);ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill()});ctx.fillStyle='#9aa3b2';ctx.font='20px -apple-system';ctx.fillText(fmtDate(rows[0].date).slice(0,6),pad.l,h-12);const end=fmtDate(rows.at(-1).date).slice(0,6);ctx.fillText(end,w-pad.r-80,h-12)}
function renderAll(){renderDashboard();renderLists();if(document.querySelector('[data-view="history"]').classList.contains('active'))drawChart()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>b.classList.contains('more-button')?$('moreSheet').classList.remove('hidden'):showView(b.dataset.target)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.go)));$('closeSheet').addEventListener('click',()=>$('moreSheet').classList.add('hidden'));$('moreSheet').addEventListener('click',e=>{if(e.target===$('moreSheet'))$('moreSheet').classList.add('hidden')});
['stress','energy','hunger','strengthRpe','runRpe'].forEach(id=>$(id).addEventListener('input',updateRanges));
$('dailyDate').addEventListener('change',e=>fillDaily(e.target.value));$('supplementDate').addEventListener('change',e=>fillSupp(e.target.value));$('nutritionDate').addEventListener('change',e=>fillNutrition(e.target.value));
$('dailyForm').addEventListener('submit',e=>{e.preventDefault();const d=$('dailyDate').value;data.daily[d]={weight:$('weight').value,waist:$('waist').value,sleep:$('sleep').value,water:$('water').value,stress:num($('stress').value),energy:num($('energy').value),hunger:num($('hunger').value),note:$('dailyNote').value.trim()};save();toast('Journée enregistrée')});
$('supplementForm').addEventListener('submit',e=>{e.preventDefault();const d=$('supplementDate').value;data.supplements[d]={creatineTaken:$('creatineTaken').checked,creatineAmount:num($('creatineAmount').value),proteinPowderTaken:$('proteinPowderTaken').checked,proteinPowderAmount:num($('proteinPowderAmount').value),other:$('otherSupplements').value.trim()};save();toast('Compléments enregistrés')});
$('nutritionForm').addEventListener('submit',e=>{e.preventDefault();const d=$('nutritionDate').value;data.nutrition[d]={protein:num($('protein').value),mealsQuality:num($('mealsQuality').value),dietDeviation:$('dietDeviation').value,note:$('nutritionNote').value.trim()};save();toast('Nutrition enregistrée')});
$('strengthForm').addEventListener('submit',e=>{e.preventDefault();data.strength.push({id:crypto.randomUUID(),date:$('strengthDate').value,type:$('strengthType').value,duration:num($('strengthDuration').value),exercises:$('strengthExercises').value.trim(),rpe:num($('strengthRpe').value),note:$('strengthNote').value.trim()});save();e.target.reset();$('strengthDate').value=today();$('strengthDuration').value=40;$('strengthRpe').value=7;updateRanges();toast('Séance ajoutée')});
$('runForm').addEventListener('submit',e=>{e.preventDefault();data.running.push({id:crypto.randomUUID(),date:$('runDate').value,type:$('runType').value,distance:num($('runDistance').value),duration:num($('runDuration').value),hr:num($('runHr').value),rpe:num($('runRpe').value),note:$('runNote').value.trim()});save();e.target.reset();$('runDate').value=today();$('runRpe').value=6;updateRanges();toast('Sortie ajoutée')});
document.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;const key=b.dataset.delete;data[key]=data[key].filter(x=>x.id!==b.dataset.id);save();toast('Entrée supprimée')});
$('chartMetric').addEventListener('change',drawChart);
$('exportBtn').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`luis-transformation-${today()}.json`;a.click();URL.revokeObjectURL(url);toast('Export créé')});
$('importInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(!parsed.daily||!parsed.strength||!parsed.running)throw new Error();data={...structuredClone(initialData),...parsed};save();fillDaily(today());fillSupp(today());fillNutrition(today());toast('Données importées')}catch{alert('Fichier invalide ou incompatible.')}e.target.value=''});
$('clearAllBtn').addEventListener('click',()=>{if(confirm('Effacer définitivement toutes les données enregistrées sur cet appareil ?')){data=structuredClone(initialData);save();fillDaily(today());fillSupp(today());fillNutrition(today());toast('Toutes les données sont effacées')}});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
setDefaults();fillDaily(today());fillSupp(today());fillNutrition(today());updateRanges();renderAll();
