'use strict';
const STORAGE_KEY='luis-transformation-v1';
const SCHEMA_VERSION=7;
const BACKUP_PREFIX='luis-transformation-backup-';
const TEMP_KEY='luis-transformation-write-temp';
const MAX_LOCAL_BACKUPS=3;
const DEFAULT_FOODS=[
{id:'chicken',name:'Blanc de poulet',kcal:165,protein:31,carbs:0,fat:3.6},{id:'skyr',name:'Skyr nature',kcal:63,protein:11,carbs:4,fat:.2},{id:'rice',name:'Riz basmati cuit',kcal:130,protein:2.7,carbs:28,fat:.3},{id:'oats',name:'Flocons d’avoine',kcal:372,protein:13.5,carbs:58.7,fat:7},{id:'banana',name:'Banane',kcal:89,protein:1.1,carbs:22.8,fat:.3},{id:'egg',name:'Œuf entier',kcal:143,protein:12.6,carbs:.7,fat:9.5},{id:'salmon',name:'Saumon',kcal:208,protein:20,carbs:0,fat:13},{id:'whey',name:'Whey isolate',kcal:370,protein:84,carbs:3,fat:1.5},{id:'greek',name:'Yaourt grec 0%',kcal:59,protein:10.3,carbs:3.6,fat:.4},{id:'pasta',name:'Pâtes cuites',kcal:157,protein:5.8,carbs:30.9,fat:.9},{id:'oliveoil',name:'Huile d’olive',kcal:884,protein:0,carbs:0,fat:100},{id:'avocado',name:'Avocat',kcal:160,protein:2,carbs:8.5,fat:14.7},{id:'bread',name:'Pain complet',kcal:247,protein:13,carbs:41,fat:4.2},{id:'beef',name:'Bœuf maigre',kcal:180,protein:27,carbs:0,fat:8},{id:'potato',name:'Pomme de terre cuite',kcal:87,protein:1.9,carbs:20,fat:.1}
];
const MEALS={breakfast:'Petit-déjeuner',lunch:'Déjeuner',snack:'Collation',dinner:'Dîner'};
const WORKOUT_PRESETS={
Push:{target:'Pectoraux · épaules · triceps',exercises:[
{name:'Développé couché barre',sets:4,reps:'6–8',rest:'2 min'},
{name:'Développé incliné haltères',sets:3,reps:'8–10',rest:'90 s'},
{name:'Développé épaules haltères',sets:3,reps:'8–10',rest:'90 s'},
{name:'Élévations latérales',sets:3,reps:'12–15',rest:'60 s'},
{name:'Dips ou pompes',sets:3,reps:'8–12',rest:'90 s'},
{name:'Extension triceps poulie',sets:3,reps:'10–15',rest:'60 s'},
{name:'Crunch à la poulie',sets:3,reps:'12–15',rest:'45 s',core:true},
{name:'Relevés de genoux suspendu',sets:3,reps:'8–12',rest:'45 s',core:true}]},
Pull:{target:'Dos · arrière d’épaules · biceps',exercises:[
{name:'Tractions assistées ou tirage vertical',sets:4,reps:'6–10',rest:'2 min'},
{name:'Rowing barre ou machine',sets:4,reps:'8–10',rest:'90 s'},
{name:'Tirage horizontal poulie',sets:3,reps:'10–12',rest:'90 s'},
{name:'Face pull',sets:3,reps:'12–15',rest:'60 s'},
{name:'Curl haltères',sets:3,reps:'8–12',rest:'60 s'},
{name:'Curl marteau',sets:2,reps:'10–12',rest:'60 s'},
{name:'Relevés de jambes suspendu',sets:3,reps:'8–12',rest:'45 s',core:true},
{name:'Gainage latéral',sets:3,reps:'30–45 s / côté',rest:'30 s',core:true}]},
Legs:{target:'Quadriceps · ischios · fessiers · mollets',exercises:[
{name:'Squat',sets:4,reps:'6–8',rest:'2 min'},
{name:'Presse à cuisses',sets:3,reps:'8–12',rest:'90 s'},
{name:'Soulevé de terre roumain',sets:3,reps:'8–10',rest:'90 s'},
{name:'Fentes marchées',sets:3,reps:'10 / jambe',rest:'75 s'},
{name:'Leg curl',sets:3,reps:'10–15',rest:'60 s'},
{name:'Mollets debout',sets:3,reps:'12–20',rest:'60 s'},
{name:'Ab wheel',sets:3,reps:'6–12',rest:'45 s',core:true},
{name:'Planche',sets:3,reps:'40–60 s',rest:'30 s',core:true}]},
'Haut du corps':{target:'Pectoraux · dos · épaules · bras',exercises:[
{name:'Développé couché',sets:4,reps:'6–8',rest:'2 min'},
{name:'Tirage vertical',sets:4,reps:'8–10',rest:'90 s'},
{name:'Développé épaules',sets:3,reps:'8–10',rest:'90 s'},
{name:'Rowing assis',sets:3,reps:'8–12',rest:'90 s'},
{name:'Superset biceps / triceps',sets:3,reps:'10–12',rest:'60 s'},
{name:'Crunch poulie',sets:3,reps:'12–15',rest:'45 s',core:true},
{name:'Pallof press',sets:3,reps:'10–12 / côté',rest:'30 s',core:true}]},
'Bas du corps':{target:'Jambes · fessiers · gainage',exercises:[
{name:'Squat ou hack squat',sets:4,reps:'6–10',rest:'2 min'},
{name:'Soulevé de terre roumain',sets:3,reps:'8–10',rest:'90 s'},
{name:'Presse à cuisses',sets:3,reps:'10–12',rest:'90 s'},
{name:'Leg curl',sets:3,reps:'10–15',rest:'60 s'},
{name:'Gainage',sets:3,reps:'40–60 s',rest:'45 s',core:true},
{name:'Ab wheel',sets:3,reps:'6–12',rest:'45 s',core:true}]},
'Full body':{target:'Corps entier',exercises:[
{name:'Squat',sets:3,reps:'6–8',rest:'2 min'},
{name:'Développé couché',sets:3,reps:'6–8',rest:'2 min'},
{name:'Tirage vertical',sets:3,reps:'8–10',rest:'90 s'},
{name:'Soulevé de terre roumain',sets:3,reps:'8–10',rest:'90 s'},
{name:'Développé épaules',sets:2,reps:'8–12',rest:'75 s'},
{name:'Circuit abdos',sets:3,reps:'12 crunchs · 10 genoux · 40 s planche',rest:'45 s',core:true}]}}
let activeWorkoutExercises=[];
function latestExerciseWeight(name){for(const w of [...data.strength].sort((a,b)=>b.date.localeCompare(a.date))){const ex=(w.workoutExercises||[]).find(x=>x.name===name&&num(x.weight)>0);if(ex)return num(ex.weight)}return ''}
function renderWorkoutPreset(){const type=$('strengthType').value,preset=WORKOUT_PRESETS[type]||WORKOUT_PRESETS.Push;$('workoutTitle').textContent=`Séance ${type}`;$('workoutTarget').textContent=preset.target;activeWorkoutExercises=preset.exercises.map((e,i)=>({...e,weight:latestExerciseWeight(e.name),done:false,index:i}));$('exerciseRows').innerHTML=activeWorkoutExercises.map((e,i)=>`<article class="exercise-row ${e.core?'core-card':''}"><div class="exercise-main"><span class="exercise-tag">${e.core?'ABDOS':'EXERCICE'}</span><strong>${escapeHtml(e.name)}</strong><small>${e.sets} séries × ${e.reps} · repos ${e.rest}</small></div><label class="weight-field"><span>${e.reps.includes('s')?'Charge':'Poids'}</span><div><input type="number" step="0.5" min="0" inputmode="decimal" data-exercise-weight="${i}" value="${e.weight}" placeholder="kg"><b>kg</b></div></label></article>`).join('')}
function collectWorkoutExercises(){return activeWorkoutExercises.map((e,i)=>({...e,weight:num(document.querySelector(`[data-exercise-weight="${i}"]`)?.value)}))}

const initialData={daily:{},supplements:{},nutrition:{},strength:[],running:[],customFoods:[],photos:[],profile:{initialWeight:81.5,initialWaist:92,proteinGoal:170,calorieGoal:2400,creatineGoal:5}};
let data=loadData(),selectedFood=null,deferredPrompt=null;
const $=id=>document.getElementById(id),today=()=>{const d=new Date(),y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return `${y}-${m}-${day}`},num=(v,fb=0)=>Number.isFinite(Number(v))?Number(v):fb,fmt=n=>Math.round(n*10)/10;
function clone(v){return JSON.parse(JSON.stringify(v))}
function normalizeData(raw={}){const p=raw&&typeof raw==='object'?raw:{};return {...clone(initialData),...p,schemaVersion:SCHEMA_VERSION,daily:p.daily&&typeof p.daily==='object'?p.daily:{},supplements:p.supplements&&typeof p.supplements==='object'?p.supplements:{},nutrition:p.nutrition&&typeof p.nutrition==='object'?p.nutrition:{},strength:Array.isArray(p.strength)?p.strength:[],running:Array.isArray(p.running)?p.running:[],customFoods:Array.isArray(p.customFoods)?p.customFoods:[],photos:Array.isArray(p.photos)?p.photos:[],profile:{...initialData.profile,...(p.profile||{})}}}
function parseStored(key){const raw=localStorage.getItem(key);if(!raw)return null;const parsed=JSON.parse(raw);return normalizeData(parsed)}
function backupKeys(){return Object.keys(localStorage).filter(k=>k.startsWith(BACKUP_PREFIX)).sort().reverse()}
function loadData(){try{const primary=parseStored(STORAGE_KEY);if(primary)return primary}catch(e){console.warn('Données principales illisibles',e)}for(const key of backupKeys()){try{const backup=parseStored(key);if(backup){localStorage.setItem(STORAGE_KEY,JSON.stringify(backup));return backup}}catch(e){console.warn('Sauvegarde illisible',key,e)}}return normalizeData(initialData)}
function rotateBackups(){const keys=backupKeys();keys.slice(MAX_LOCAL_BACKUPS).forEach(k=>localStorage.removeItem(k))}
function save(){try{const previous=localStorage.getItem(STORAGE_KEY);if(previous){const stamp=new Date().toISOString().replace(/[:.]/g,'-');localStorage.setItem(`${BACKUP_PREFIX}${stamp}`,previous)}data=normalizeData(data);const payload=JSON.stringify(data);localStorage.setItem(TEMP_KEY,payload);JSON.parse(localStorage.getItem(TEMP_KEY));localStorage.setItem(STORAGE_KEY,payload);localStorage.removeItem(TEMP_KEY);rotateBackups();renderAll();return true}catch(e){console.error('Échec de sauvegarde',e);try{localStorage.removeItem(TEMP_KEY)}catch{};alert('La sauvegarde a échoué. N’efface pas les données Safari et effectue un export complet.');return false}}
function toast(m){$('toast').textContent=m;$('toast').classList.remove('hidden');setTimeout(()=>$('toast').classList.add('hidden'),2000)}
function fmtDate(d){return new Intl.DateTimeFormat('fr-CH',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00'))}
function setDefaults(force=false){const current=today();['dailyDate','supplementDate','nutritionDate','strengthDate','runDate','photoDate'].forEach(id=>{const input=$(id);if(input&&(force||!input.value))input.value=current})}
function showView(name){setDefaults();document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.target===name));$('pageTitle').textContent={dashboard:'Tableau de bord',daily:'Saisie quotidienne',nutrition:'Nutrition',supplements:'Compléments',strength:'Musculation',running:'Course',history:'Historique',photos:'Photos progression',settings:'Plus'}[name]||'Luis Transformation';$('moreSheet').classList.add('hidden');if(name==='nutrition')renderNutrition();if(name==='history')drawChart();if(name==='photos')renderPhotos();scrollTo(0,0)}
function nutritionDay(date=today()){const n=data.nutrition[date];if(!n)return {entries:[]};if(Array.isArray(n.entries))return n;const legacyProtein=num(n.protein);return legacyProtein?{...n,entries:[],legacyProtein}:{...n,entries:[]}}
function totals(date=today(),meal=null){const n=nutritionDay(date);const list=meal?n.entries.filter(e=>e.meal===meal):n.entries;const t=list.reduce((a,e)=>({kcal:a.kcal+num(e.kcal),protein:a.protein+num(e.protein),carbs:a.carbs+num(e.carbs),fat:a.fat+num(e.fat)}),{kcal:0,protein:0,carbs:0,fat:0});if(!meal&&n.legacyProtein&&!t.protein)t.protein=n.legacyProtein;return t}
function renderNutrition(){const date=$('nutritionDate').value||today(),t=totals(date);$('nutKcal').textContent=Math.round(t.kcal);$('nutProtein').textContent=fmt(t.protein);$('nutCarbs').textContent=fmt(t.carbs);$('nutFat').textContent=fmt(t.fat);$('kcalBar').style.width=`${Math.min(100,t.kcal/data.profile.calorieGoal*100)}%`;$('proteinHint').textContent=t.protein>=data.profile.proteinGoal?'Objectif protéines atteint ✅':`Il te manque ${Math.ceil(data.profile.proteinGoal-t.protein)} g de protéines.`;const host=$('mealSections');host.innerHTML='';Object.entries(MEALS).forEach(([key,label])=>{const n=nutritionDay(date),list=n.entries.filter(e=>e.meal===key),mt=totals(date,key),sec=document.createElement('section');sec.className='card section-card';sec.innerHTML=`<div class="meal-head"><h2 class="meal-title">${label}</h2><span class="meal-total">${Math.round(mt.kcal)} kcal · ${fmt(mt.protein)} g prot.</span></div>${list.length?list.map(e=>`<div class="food-row"><div><strong>${escapeHtml(e.name)}</strong><small>${e.grams} g · ${Math.round(e.kcal)} kcal · ${fmt(e.protein)} g prot.</small></div><button class="delete" data-food-delete="${e.id}">×</button></div>`).join(''):'<div class="empty">Aucun aliment</div>'}`;host.appendChild(sec)});renderFoodSearch($('foodSearch').value)}
function foods(){return [...data.customFoods,...DEFAULT_FOODS]}function renderFoodSearch(q=''){const s=q.trim().toLowerCase(),list=(s?foods().filter(f=>f.name.toLowerCase().includes(s)):foods().slice(0,7)).slice(0,12);$('foodResults').innerHTML=list.map(f=>`<div class="food-result" data-food="${f.id}"><div><strong>${escapeHtml(f.name)}</strong><small>pour 100 g</small></div><small>${f.kcal} kcal · ${f.protein} g prot.</small></div>`).join('')}
function openFood(f){selectedFood=f;$('dialogFoodName').textContent=f.name;$('dialogFoodMacros').textContent=`Pour 100 g : ${f.kcal} kcal · ${f.protein} g protéines · ${f.carbs} g glucides · ${f.fat} g lipides`;$('gramsInput').value=100;$('foodDialog').showModal()}
function latestDaily(field,fallback){const r=Object.entries(data.daily).filter(([,v])=>v[field]!==''&&v[field]!=null).sort(([a],[b])=>b.localeCompare(a));return r.length?num(r[0][1][field],fallback):fallback}
function getWeekBounds(){const d=new Date(),day=(d.getDay()+6)%7,start=new Date(d);start.setDate(d.getDate()-day);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(start.getDate()+6);return{start,end}}function inCurrentWeek(ds){const d=new Date(ds+'T12:00:00'),{start,end}=getWeekBounds();return d>=start&&d<=end}
function renderDashboard(){const date=today(),daily=data.daily[date]||{},sup=data.supplements[date]||{},t=totals(date),weight=latestDaily('weight',data.profile.initialWeight),waist=latestDaily('waist',data.profile.initialWaist);$('todayLabel').textContent=new Intl.DateTimeFormat('fr-CH',{weekday:'long',day:'numeric',month:'long'}).format(new Date());$('currentWeight').textContent=`${weight.toFixed(1).replace('.',',')} kg`;$('currentWaist').textContent=`${waist.toFixed(1).replace('.',',')} cm`;$('weightDelta').textContent=`${(weight-data.profile.initialWeight).toFixed(1)} kg`;$('waistDelta').textContent=`${(waist-data.profile.initialWaist).toFixed(1)} cm`;$('caloriesToday').textContent=`${Math.round(t.kcal)} / ${data.profile.calorieGoal}`;$('calorieStatus').textContent=t.kcal>=data.profile.calorieGoal*.9?'Bien avancé':'À compléter';$('proteinToday').textContent=`${fmt(t.protein)} / ${data.profile.proteinGoal} g`;$('proteinStatus').textContent=t.protein>=data.profile.proteinGoal?'Objectif atteint':'À compléter';const creatine=sup.creatineTaken?num(sup.creatineAmount,5):0;let checks=0;if(daily.weight)checks++;if(daily.waist)checks++;if(daily.sleep)checks++;if(daily.water)checks++;if(t.protein>=data.profile.proteinGoal)checks++;if(creatine>=5)checks++;if(data.strength.some(x=>x.date===date)||data.running.some(x=>x.date===date))checks++;$('dayScore').textContent=Math.round(checks/7*100);const strength=data.strength.filter(x=>inCurrentWeek(x.date)).length,runs=data.running.filter(x=>inCurrentWeek(x.date)).length,creatineDays=Object.entries(data.supplements).filter(([d,v])=>inCurrentWeek(d)&&v.creatineTaken&&num(v.creatineAmount)>=5).length;$('strengthProgress').value=Math.min(strength,4);$('runProgress').value=Math.min(runs,3);$('creatineProgress').value=Math.min(creatineDays,7);$('strengthCount').textContent=`${strength}/4`;$('runCount').textContent=`${runs}/3`;$('creatineCount').textContent=`${creatineDays}/7`;const {start,end}=getWeekBounds();$('weekRange').textContent=`${start.getDate()}–${end.getDate()}`;const pc=$('photoCount');if(pc)pc.textContent=`${(data.photos||[]).length} photo${(data.photos||[]).length>1?'s':''}`}
function fillDaily(d){const v=data.daily[d]||{};['weight','waist','sleep','water'].forEach(k=>$(k).value=v[k]??'');$('stress').value=v.stress??3;$('energy').value=v.energy??3;$('hunger').value=v.hunger??3;$('dailyNote').value=v.note??'';updateRanges()}function fillSupp(d){const v=data.supplements[d]||{};$('creatineTaken').checked=!!v.creatineTaken;$('creatineAmount').value=v.creatineAmount??5;$('proteinPowderTaken').checked=!!v.proteinPowderTaken;$('proteinPowderAmount').value=v.proteinPowderAmount??30;$('otherSupplements').value=v.other??''}
function updateRanges(){['stress','energy','hunger','strengthRpe','runRpe'].forEach(id=>{const o=$(id+'Out');if(o)o.textContent=`${$(id).value}/${$(id).max}`})}function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderLists(){const mk=(x,type)=>{const detail=type==='strength'&&x.workoutExercises?.length?x.workoutExercises.map(e=>`${e.name} · ${e.sets}×${e.reps} · ${e.weight||0} kg`).join('\n'):escapeHtml(x.exercises||x.note||'');return `<article class="entry"><div class="entry-head"><div><h4>${type==='strength'?escapeHtml(x.type):`${escapeHtml(x.type)} — ${x.distance} km`}</h4><span class="muted">${fmtDate(x.date)}</span></div><button class="delete-entry" data-delete="${type}" data-id="${x.id}">×</button></div><p>${type==='strength'&&x.workoutExercises?.length?escapeHtml(detail):detail}</p></article>`};$('strengthList').innerHTML=[...data.strength].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=>mk(x,'strength')).join('');$('runList').innerHTML=[...data.running].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8).map(x=>mk(x,'running')).join('');$('historyList').innerHTML=Object.entries(data.daily).sort(([a],[b])=>b.localeCompare(a)).slice(0,12).map(([d,v])=>`<article class="entry"><h4>${fmtDate(d)}</h4><div class="entry-meta">${v.weight?`<span class="chip">${v.weight} kg</span>`:''}${v.waist?`<span class="chip">${v.waist} cm</span>`:''}</div></article>`).join('')}
function drawChart(){const metric=$('chartMetric').value;let rows;if(['protein','calories'].includes(metric))rows=Object.keys(data.nutrition).map(date=>({date,value:metric==='protein'?totals(date).protein:totals(date).kcal}));else rows=Object.entries(data.daily).map(([date,v])=>({date,value:num(v[metric],NaN)}));rows=rows.filter(x=>Number.isFinite(x.value)).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);const c=$('progressChart'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);$('chartEmpty').classList.toggle('hidden',rows.length>=2);if(rows.length<2)return;const vals=rows.map(x=>x.value),min=Math.min(...vals),max=Math.max(...vals),range=max-min||1,p={l:55,r:20,t:25,b:35};ctx.strokeStyle='#79e6a3';ctx.lineWidth=5;ctx.beginPath();rows.forEach((r,i)=>{const x=p.l+(w-p.l-p.r)*i/(rows.length-1),y=p.t+(max-r.value)/range*(h-p.t-p.b);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}

async function lookupBarcode(code){
  const clean=String(code||'').replace(/\D/g,'');
  if(!clean)return toast('Code-barres invalide');
  toast('Recherche du produit…');
  try{
    const r=await fetch(`https://world.openfoodfacts.org/api/v2/product/${clean}.json`);
    const j=await r.json();
    if(j.status!==1)throw new Error('not found');
    const p=j.product||{},n=p.nutriments||{};
    const food={id:`barcode-${clean}`,barcode:clean,name:p.product_name_fr||p.product_name||`Produit ${clean}`,kcal:num(n['energy-kcal_100g']),protein:num(n.proteins_100g),carbs:num(n.carbohydrates_100g),fat:num(n.fat_100g)};
    if(!food.kcal&&!food.protein)throw new Error('missing nutrition');
    const existing=data.customFoods.findIndex(x=>x.id===food.id);if(existing>=0)data.customFoods[existing]=food;else data.customFoods.unshift(food);save();openFood(food);
  }catch(e){toast('Produit introuvable — ajoute-le manuellement')}
}
async function startBarcodeScan(){
  if(!('BarcodeDetector' in window)){const code=prompt('La caméra de scan n’est pas disponible sur cet iPhone. Saisis les chiffres du code-barres :');if(code)lookupBarcode(code);return}
  try{
    const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}}),video=$('barcodeVideo'),dlg=$('barcodeDialog');video.srcObject=stream;dlg.showModal();await video.play();
    const detector=new BarcodeDetector({formats:['ean_13','ean_8','upc_a','upc_e']});let stopped=false;
    const stop=()=>{stopped=true;stream.getTracks().forEach(t=>t.stop());if(dlg.open)dlg.close()};$('closeBarcode').onclick=stop;
    const loop=async()=>{if(stopped)return;try{const codes=await detector.detect(video);if(codes[0]){const raw=codes[0].rawValue;stop();lookupBarcode(raw);return}}catch{}requestAnimationFrame(loop)};loop();
  }catch{const code=prompt('Autorisation caméra impossible. Saisis le code-barres :');if(code)lookupBarcode(code)}
}
function parseDuration(v){if(!v)return 0;const p=String(v).trim().split(':').map(Number);return p.length===3?p[0]*60+p[1]+p[2]/60:p.length===2?p[0]+p[1]/60:num(v)}
function xmlText(doc,names){for(const n of names){const el=doc.getElementsByTagName(n)[0]||doc.getElementsByTagNameNS('*',n)[0];if(el?.textContent)return el.textContent}return ''}
async function importGarminFile(file){
  const ext=file.name.split('.').pop().toLowerCase();if(ext==='fit')return toast('FIT brut : exporte l’activité Garmin en GPX, TCX ou CSV');
  try{let run={id:crypto.randomUUID(),type:'Garmin',rpe:6,note:`Import Garmin · ${file.name}`};
    if(['gpx','tcx'].includes(ext)){const doc=new DOMParser().parseFromString(await file.text(),'application/xml');const time=xmlText(doc,['Time','time']);run.date=(time||today()).slice(0,10);let pts=[...doc.getElementsByTagNameNS('*','trkpt')].map(n=>({lat:+n.getAttribute('lat'),lon:+n.getAttribute('lon')})).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon));if(!pts.length){pts=[...doc.getElementsByTagNameNS('*','Trackpoint')].map(n=>({lat:num(xmlText(n,['LatitudeDegrees'])),lon:num(xmlText(n,['LongitudeDegrees']))})).filter(p=>p.lat&&p.lon)}run.route=pts.filter((_,i)=>i%Math.max(1,Math.floor(pts.length/600))===0);let dist=num(xmlText(doc,['DistanceMeters']))/1000;if(!dist&&pts.length>1){let m=0;for(let i=1;i<pts.length;i++){const a=pts[i-1],b=pts[i],R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLon=(b.lon-a.lon)*Math.PI/180,q=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLon/2)**2;m+=2*R*Math.asin(Math.sqrt(q))}dist=m}run.distance=fmt(dist);let sec=num(xmlText(doc,['TotalTimeSeconds']));if(!sec){const times=[...doc.getElementsByTagNameNS('*','time'),...doc.getElementsByTagNameNS('*','Time')].map(n=>Date.parse(n.textContent)).filter(Number.isFinite);if(times.length>1)sec=(Math.max(...times)-Math.min(...times))/1000}run.duration=fmt(sec/60);run.hr=num(xmlText(doc,['AverageHeartRateBpm','Value']));run.elevation=num(xmlText(doc,['ElevationGain']));}
    else if(ext==='csv'){const lines=(await file.text()).split(/\r?\n/).filter(Boolean),sep=lines[0].includes(';')?';':',';const h=lines[0].split(sep).map(x=>x.replace(/"/g,'').trim().toLowerCase()),v=lines[1].split(sep).map(x=>x.replace(/"/g,'').trim());const get=(...keys)=>{const i=h.findIndex(x=>keys.some(k=>x.includes(k)));return i>=0?v[i]:''};run.date=(get('date','début')||today()).slice(0,10);run.distance=num(String(get('distance')).replace(',','.'));run.duration=parseDuration(get('temps','time','durée'));run.hr=num(get('fréquence cardiaque moyenne','avg hr','fc moyenne'));run.elevation=num(get('dénivelé','elevation gain'));}
    else throw new Error('format');if(!run.distance)throw new Error('distance');data.running.push(run);save();toast('Activité Garmin importée');
  }catch{toast('Fichier Garmin non reconnu')}
}
const PHOTO_DB='luis-transformation-photos';
function photoDB(){return new Promise((ok,no)=>{const r=indexedDB.open(PHOTO_DB,1);r.onupgradeneeded=()=>r.result.createObjectStore('photos',{keyPath:'id'});r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function storePhoto(meta,file){const db=await photoDB(),rec={...meta,blob:file};await new Promise((ok,no)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put(rec);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function getPhoto(id){const db=await photoDB();return new Promise((ok,no)=>{const r=db.transaction('photos').objectStore('photos').get(id);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function deletePhoto(id){const db=await photoDB();await new Promise((ok,no)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').delete(id);tx.oncomplete=ok;tx.onerror=()=>no(tx.error)})}
async function renderPhotos(){const host=$('photoGrid');if(!host)return;host.innerHTML='<div class="empty">Chargement…</div>';const items=[...(data.photos||[])].sort((a,b)=>b.date.localeCompare(a.date));if(!items.length){host.innerHTML='<div class="empty card">Ajoute ta première photo pour créer ton avant/après.</div>';return}const cards=[];for(const m of items){try{const r=await getPhoto(m.id),url=r?.blob?URL.createObjectURL(r.blob):'';cards.push(`<article class="photo-card card"><img src="${url}" alt="Progression ${m.date}"><div><strong>${fmtDate(m.date)} · ${escapeHtml(m.pose)}</strong><small>${m.weight||'—'} kg · ${m.waist||'—'} cm</small><p>${escapeHtml(m.note||'')}</p><button class="delete-photo danger-text" data-photo-delete="${m.id}">Supprimer</button></div></article>`)}catch{}}host.innerHTML=cards.join('')}

function renderAll(){renderDashboard();renderLists();if(document.querySelector('[data-view="nutrition"]').classList.contains('active'))renderNutrition();if(document.querySelector('[data-view="photos"]').classList.contains('active'))renderPhotos()}
document.querySelectorAll('.nav-item').forEach(b=>b.addEventListener('click',()=>b.classList.contains('more-button')?$('moreSheet').classList.remove('hidden'):showView(b.dataset.target)));document.querySelectorAll('[data-go]').forEach(el=>{
  el.addEventListener('click',()=>showView(el.dataset.go));
  if(el.getAttribute('role')==='button') el.addEventListener('keydown',e=>{
    if(e.key==='Enter'||e.key===' '){e.preventDefault();showView(el.dataset.go)}
  });
});$('closeSheet').onclick=()=>$('moreSheet').classList.add('hidden');['stress','energy','hunger','strengthRpe','runRpe'].forEach(id=>$(id).oninput=updateRanges);$('strengthType').onchange=renderWorkoutPreset;if($('comparePose'))$('comparePose').onchange=renderPhotoAnalysis;
$('dailyDate').onchange=e=>fillDaily(e.target.value);$('supplementDate').onchange=e=>fillSupp(e.target.value);$('nutritionDate').onchange=renderNutrition;$('foodSearch').oninput=e=>renderFoodSearch(e.target.value);$('toggleCustomFood').onclick=()=>$('customFoodForm').classList.toggle('hidden');
$('dailyForm').onsubmit=e=>{e.preventDefault();const d=$('dailyDate').value;data.daily[d]={weight:$('weight').value,waist:$('waist').value,sleep:$('sleep').value,water:$('water').value,stress:num($('stress').value),energy:num($('energy').value),hunger:num($('hunger').value),note:$('dailyNote').value.trim()};save();toast('Journée enregistrée')};
$('supplementForm').onsubmit=e=>{e.preventDefault();const d=$('supplementDate').value;data.supplements[d]={creatineTaken:$('creatineTaken').checked,creatineAmount:num($('creatineAmount').value),proteinPowderTaken:$('proteinPowderTaken').checked,proteinPowderAmount:num($('proteinPowderAmount').value),other:$('otherSupplements').value.trim()};save();toast('Compléments enregistrés')};
$('strengthForm').onsubmit=e=>{e.preventDefault();const workoutExercises=collectWorkoutExercises();data.strength.push({id:crypto.randomUUID(),date:$('strengthDate').value,type:$('strengthType').value,duration:num($('strengthDuration').value),workoutExercises,exercises:workoutExercises.map(x=>`${x.name}: ${x.sets}×${x.reps} à ${x.weight||0} kg`).join('\n'),rpe:num($('strengthRpe').value),note:$('strengthNote').value.trim()});save();renderWorkoutPreset();toast('Séance enregistrée')};$('runForm').onsubmit=e=>{e.preventDefault();data.running.push({id:crypto.randomUUID(),date:$('runDate').value,type:$('runType').value,distance:num($('runDistance').value),duration:num($('runDuration').value),hr:num($('runHr').value),rpe:num($('runRpe').value),note:$('runNote').value.trim()});save();toast('Sortie ajoutée')};
$('foodResults').onclick=e=>{const el=e.target.closest('[data-food]');if(el)openFood(foods().find(f=>f.id===el.dataset.food))};$('confirmFood').onclick=e=>{e.preventDefault();const grams=num($('gramsInput').value);if(!selectedFood||grams<1)return;const d=$('nutritionDate').value,n=nutritionDay(d),r=grams/100;n.entries.push({id:crypto.randomUUID(),meal:$('mealSelect').value,name:selectedFood.name,grams,kcal:selectedFood.kcal*r,protein:selectedFood.protein*r,carbs:selectedFood.carbs*r,fat:selectedFood.fat*r});data.nutrition[d]=n;save();$('foodDialog').close();toast('Aliment ajouté')};
$('customFoodForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),food={id:`custom-${Date.now()}`,name:f.get('name'),kcal:num(f.get('kcal')),protein:num(f.get('protein')),carbs:num(f.get('carbs')),fat:num(f.get('fat'))};data.customFoods.unshift(food);save();e.target.reset();e.target.classList.add('hidden');toast('Aliment créé')};
$('mealSections').onclick=e=>{const b=e.target.closest('[data-food-delete]');if(!b)return;const d=$('nutritionDate').value,n=nutritionDay(d);n.entries=n.entries.filter(x=>x.id!==b.dataset.foodDelete);data.nutrition[d]=n;save()};$('copyYesterday').onclick=()=>{const d=new Date(($('nutritionDate').value||today())+'T12:00:00');d.setDate(d.getDate()-1);const prev=d.toISOString().slice(0,10),src=nutritionDay(prev);if(!src.entries.length)return toast('Aucun repas la veille');data.nutrition[$('nutritionDate').value]={entries:src.entries.map(x=>({...x,id:crypto.randomUUID()}))};save();toast('Journée copiée')};
document.addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;data[b.dataset.delete]=data[b.dataset.delete].filter(x=>x.id!==b.dataset.id);save()});$('scanBarcodeBtn').onclick=startBarcodeScan;$('barcodeManualBtn').onclick=()=>{const c=prompt('Saisis les chiffres du code-barres :');if(c)lookupBarcode(c)};
$('garminImport').onchange=e=>{const f=e.target.files[0];if(f)importGarminFile(f);e.target.value=''};
$('photoForm').onsubmit=async e=>{e.preventDefault();const file=$('photoFile').files[0];if(!file)return toast('Choisis une photo');const id=crypto.randomUUID(),meta={id,date:$('photoDate').value,pose:$('photoPose').value,weight:$('photoWeight').value,waist:$('photoWaist').value,note:$('photoNote').value.trim()};try{await storePhoto(meta,file);data.photos=[...(data.photos||[]),meta];save();e.target.reset();$('photoDate').value=today();renderPhotos();toast('Photo enregistrée sur cet appareil')}catch{toast('Impossible d’enregistrer la photo')}};
$('photoGrid').onclick=async e=>{const b=e.target.closest('[data-photo-delete]');if(!b)return;await deletePhoto(b.dataset.photoDelete);data.photos=(data.photos||[]).filter(x=>x.id!==b.dataset.photoDelete);save();renderPhotos()};
function blobToDataURL(blob){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=()=>no(r.error);r.readAsDataURL(blob)})}
function dataURLToBlob(url){const [head,body]=url.split(',');const mime=(head.match(/data:(.*?);/)||[])[1]||'image/jpeg';const bin=atob(body),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return new Blob([arr],{type:mime})}
async function fullBackupPayload(){const payload={format:'luis-transformation-full-backup',schemaVersion:SCHEMA_VERSION,exportedAt:new Date().toISOString(),origin:location.origin,data:normalizeData(data),photoFiles:[]};for(const meta of payload.data.photos||[]){try{const rec=await getPhoto(meta.id);if(rec?.blob)payload.photoFiles.push({id:meta.id,type:rec.blob.type||'image/jpeg,data',dataUrl:await blobToDataURL(rec.blob)})}catch(e){console.warn('Photo non exportée',meta.id,e)}}return payload}
$('chartMetric').onchange=drawChart;$('exportBtn').onclick=async()=>{try{toast('Préparation de la sauvegarde complète…');const payload=await fullBackupPayload(),a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(payload)],{type:'application/json'}));a.href=url;a.download=`luis-transformation-backup-complet-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast(`Sauvegarde créée · ${payload.photoFiles.length} photo(s)`)}catch(e){console.error(e);alert('Impossible de créer la sauvegarde complète')}};$('importInput').onchange=async e=>{try{const parsed=JSON.parse(await e.target.files[0].text()),incoming=parsed?.format==='luis-transformation-full-backup'?parsed.data:parsed;data=normalizeData(incoming);if(Array.isArray(parsed.photoFiles)){for(const item of parsed.photoFiles){const meta=(data.photos||[]).find(x=>x.id===item.id);if(meta&&item.dataUrl)await storePhoto(meta,dataURLToBlob(item.dataUrl))}}if(save())toast('Données et photos restaurées')}catch(err){console.error(err);alert('Fichier de sauvegarde invalide ou incomplet')}finally{e.target.value=''}};$('clearAllBtn').onclick=()=>{if(confirm('Effacer toutes les données de suivi ? Une sauvegarde complète est recommandée avant.')){data=clone(initialData);save()}};
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('installBtn').classList.remove('hidden')});$('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
document.addEventListener('DOMContentLoaded',()=>{setDefaults();fillDaily(today());fillSupp(today());updateRanges();renderWorkoutPreset();renderAll()});
